import Vue from 'vue'
import {
  Pagination,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Input,
  InputNumber,
  Radio,
  RadioButton,
  Checkbox,
  CheckboxButton,
  Switch,
  Select,
  Option,
  Button,
  Table,
  TimeSelect,
  TimePicker,
  Tooltip,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Alert,
  Slider,
  Icon,
  Col,
  Upload,
  Progress,
  Carousel,
  CarouselItem,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Link,
  Divider,
  Image
} from 'element-ui'

Vue.prototype.$ELEMENT = { size: 'small', zIndex: 3000 }

Vue.use(Pagination)
  .use(Autocomplete)
  .use(Dropdown)
  .use(DropdownMenu)
  .use(DropdownItem)
  .use(Menu)
  .use(Input)
  .use(InputNumber)
  .use(Radio)
  .use(RadioButton)
  .use(Checkbox)
  .use(CheckboxButton)
  .use(Switch)
  .use(Option)
  .use(Button)
  .use(Table)
  .use(TimeSelect)
  .use(TimePicker)
  .use(Breadcrumb)
  .use(BreadcrumbItem)
  .use(Form)
  .use(FormItem)
  .use(Tooltip)
  .use(Tabs)
  .use(TabPane)
  .use(Alert)
  .use(Slider)
  .use(Select)
  .use(Icon)
  .use(Col)
  .use(Upload)
  .use(Progress)
  .use(Carousel)
  .use(CarouselItem)
  .use(Container)
  .use(Header)
  .use(Aside)
  .use(Main)
  .use(Footer)
  .use(Link)
  .use(Divider)
  .use(Image)
